import type { TemplateConfig } from "@/types";

export const template01Config: TemplateConfig = {
  id: "template-01",
  name: "Elegant Ivory",
  description: "Minimal ivory design with champagne gold accents and elegant serif typography.",
  price: 299,
  previewImage: "/templates/template-01-preview.jpg",
  active: true,
  steps: [
    { id: 1, title: "The Couple", description: "Names of the bride and groom" },
    { id: 2, title: "Wedding Details", description: "Date, time, and venue" },
    { id: 3, title: "Photos", description: "Main photo and gallery" },
    { id: 4, title: "Your Story", description: "Share your love story" },
    { id: 5, title: "Preview", description: "Review your invitation" },
  ],
  fields: [
    { name: "groomName", label: "Groom Name", type: "text", required: true, step: 1 },
    { name: "brideName", label: "Bride Name", type: "text", required: true, step: 1 },
    {
      name: "weddingDate",
      label: "Wedding Date",
      type: "date",
      required: true,
      step: 2,
    },
    {
      name: "weddingTime",
      label: "Wedding Time",
      type: "time",
      required: true,
      step: 2,
    },
    { name: "venue", label: "Venue Name", type: "text", required: true, step: 2 },
    { name: "location", label: "Address", type: "text", required: true, step: 2 },
    {
      name: "googleMapsUrl",
      label: "Google Maps URL",
      type: "url",
      required: false,
      step: 2,
    },
    { name: "mainImage", label: "Main Photo", type: "image", required: false, step: 3 },
    { name: "gallery", label: "Gallery Photos", type: "gallery", required: false, step: 3 },
    { name: "story", label: "Your Love Story", type: "textarea", required: false, step: 4 },
    {
      name: "rsvpEnabled",
      label: "Enable RSVP Section",
      type: "boolean",
      required: false,
      step: 4,
    },
    {
      name: "guestWishesEnabled",
      label: "Enable Guest Wishes",
      type: "boolean",
      required: false,
      step: 4,
    },
  ],
};

export const template02Config: TemplateConfig = {
  id: "template-02",
  name: "Midnight Gold",
  description: "Luxury dark theme with dramatic gold accents and bold animations.",
  price: 399,
  previewImage: "/templates/template-02-preview.jpg",
  active: true,
  steps: [
    { id: 1, title: "The Couple", description: "Names of the bride and groom" },
    { id: 2, title: "Event Details", description: "Date, time, and venue" },
    { id: 3, title: "Photos", description: "Hero image" },
    { id: 4, title: "Preview", description: "Review your invitation" },
  ],
  fields: [
    { name: "groomName", label: "Groom Name", type: "text", required: true, step: 1 },
    { name: "brideName", label: "Bride Name", type: "text", required: true, step: 1 },
    { name: "weddingDate", label: "Wedding Date", type: "date", required: true, step: 2 },
    { name: "weddingTime", label: "Wedding Time", type: "time", required: true, step: 2 },
    { name: "venue", label: "Venue", type: "text", required: true, step: 2 },
    { name: "location", label: "Location", type: "text", required: true, step: 2 },
    { name: "googleMapsUrl", label: "Google Maps URL", type: "url", required: false, step: 2 },
    { name: "mainImage", label: "Hero Photo", type: "image", required: true, step: 3 },
    { name: "story", label: "Tagline / Story", type: "textarea", required: false, step: 3 },
    { name: "rsvpEnabled", label: "Enable RSVP", type: "boolean", required: false, step: 3 },
  ],
};

export const template03Config: TemplateConfig = {
  id: "template-03",
  name: "Romantic Bloom",
  description: "Soft floral romantic design with photo-focused layout and gentle animations.",
  price: 349,
  previewImage: "/templates/template-03-preview.jpg",
  active: true,
  steps: [
    { id: 1, title: "The Couple", description: "Your names" },
    { id: 2, title: "Wedding Day", description: "When and where" },
    { id: 3, title: "Memories", description: "Photos and story" },
    { id: 4, title: "Preview", description: "Review your invitation" },
  ],
  fields: [
    { name: "groomName", label: "Groom Name", type: "text", required: true, step: 1 },
    { name: "brideName", label: "Bride Name", type: "text", required: true, step: 1 },
    { name: "weddingDate", label: "Wedding Date", type: "date", required: true, step: 2 },
    { name: "weddingTime", label: "Ceremony Time", type: "time", required: true, step: 2 },
    { name: "venue", label: "Venue", type: "text", required: true, step: 2 },
    { name: "location", label: "Address", type: "text", required: false, step: 2 },
    { name: "mainImage", label: "Couple Photo", type: "image", required: true, step: 3 },
    { name: "gallery", label: "Photo Gallery", type: "gallery", required: false, step: 3 },
    { name: "story", label: "Our Story", type: "textarea", required: false, step: 3 },
  ],
};
